export interface addEnquiryForm {
	name?: any,
	phone?: any,
	email?: any,
	gender?: any,
	dob?: any,
	phone2?: any,
	email2?: any,
	curr_address?: any,
	parent_name?: any,
	parent_phone?: any,
	parent_email?: any,
	city?: any,
	area?: any,
	occupation_id?: any,
	school_id?: any,
	qualification?: any,
	grade?: any,
	enquiry_date?: any,
	standard_id?: any,
	subject_id?: any,
	subjectIdArray?: any,
	courseIdArray?: any,
	referred_by?: any,
	source_id?: any,
	fee_committed?: any,
	discount_offered?: any,
	master_course_name?: any,
	priority?: any,
	enquiry?: any,
	follow_type?: any,
	followUpDate?: any,
	religion?: any,
	link?: any,
	slot_id?: any,
	closedReason?: any,
	demo_by_id?: any,
	status?: any,
	assigned_to?: any,
	followUpTime?: any,
	lead_id?: any,
	enqCustomLi?: any,
	source_instituteId?: any,
	walkin_followUpDate: any,
	walkin_followUpTime: any,
	closing_reason_id: any,
	is_follow_up_time_notification?: any
	country_id?: any,
	state_id?: any,
	city_id?: any,
	area_id?: any,
	user_id?: any
	birth_place?: any,
	blood_group?: any,
	category?: any,
	nationality?: any,
	student_adhar_no?: any,
	parent_adhar_no?: any,
	parent_profession?: any,
	mother_tounge?:any,
	extra_curricular_activities?: any,
	educational_group?: any,
	pin_code?: any,
	inst_acad_year_id?: any,
	guardian_name?:any,
	guardian_phone?:any,
	guardian_email?:any,
	address?: any

}
