export interface instituteInfo {
    doa_from_date?:any,
    doa_to_date?:any
    institute_id?: any;
    function_type?: any;
    username?: any;
    password?: any;
    onLoad?: any;
    school?: any;
    school_id?: any;
    standard_id?: any;
    batch_id?: any;
    is_active?: any;
    is_active_status?: any;
    subject_id?: any;
    course_id?: any;
    name?: any;
    subjectIdArray?: any,
    courseIdArray?: any,
    phone?: any;
    email?: any;
    enquiry_no?: any;
    priority?: any;
    filtered_statuses?: any;
    status?: any;
    follow_type?: any;
    followUpDate?: any;
    enquiry_date?: any;
    assigned_to?: any;
    is_recent?: any;
    filtered_slots?: any;
    isDashbord?: any;
    enquireDateFrom?: any;
    enquireDateTo?: any;
    updateDate?: any;
    updateDateFrom?: any;
    updateDateTo?: any;
    is_load?: any;
    mobile?: any;
    language_inst_status?: any;
    slot_id?: any;
    master_course_name?: any;
    start_index?: any;
    batch_size?: any;
    closedReason?: any;
    enqCustomLi?: any;
    sorted_by?: any;
    order_by?: any;
    stuCustomLi?: any;
    commentShow?: any;
    source_id?: any;
    list_id?: any;
    city?: any;
    area?: any;
    referred_by?:any;
    country_id?: any;
    state_id?: any;
    city_id?: any;
    assign_to?: any;
}
